<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf3b8eacb71f3946889054ea1300157b3
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Ocooking\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Ocooking\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf3b8eacb71f3946889054ea1300157b3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf3b8eacb71f3946889054ea1300157b3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf3b8eacb71f3946889054ea1300157b3::$classMap;

        }, null, ClassLoader::class);
    }
}
